# Generated by Django 5.2.7 on 2025-11-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('project_date', models.DateField()),
                ('project_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='portfolio/')),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='service_icon',
            field=models.CharField(max_length=100),
        ),
    ]
