# Generated by Django 5.2.7 on 2025-11-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioitem_alter_services_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
